import { GeminiClient } from '../lib/GeminiClient';

export interface QueryStrategistInput {
  naturalLanguagePrompt: string;
  historicalSchema?: Record<string, any>;
  activeIncidentMetadata?: {
    serviceName: string;
    timeWindow: string;
    errorCode?: string;
  };
}

export interface QueryStrategistOutput {
  splQuery: string;
  targetIndices: string[];
  estimatedComplexity: 'low' | 'medium' | 'high';
  explanation: string;
}

export class QueryStrategistAgent {
  private gemini = new GeminiClient();

  public async execute(input: QueryStrategistInput): Promise<QueryStrategistOutput> {
    const service = input.activeIncidentMetadata?.serviceName || 'unknown-service';
    const timeWindow = input.activeIncidentMetadata?.timeWindow || '-15m';

    const prompt = `
      You are an expert Splunk SPL (Search Processing Language) developer.
      Convert the following natural language request into a highly optimized, safe Splunk SPL query.
      
      User Request: "${input.naturalLanguagePrompt}"
      Context: Service="${service}", TimeWindow="${timeWindow}"
      
      Return ONLY a JSON block with the following structure (no markdown fences, just pure JSON):
      {
        "splQuery": "...",
        "targetIndices": ["..."],
        "estimatedComplexity": "low|medium|high",
        "explanation": "..."
      }
    `;

    try {
      const responseText = await this.gemini.generateContent(prompt);
      const cleanJsonStr = responseText.replace(/```json/g, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleanJsonStr);

      return {
        splQuery: parsed.splQuery || `index=* "${service}"`,
        targetIndices: parsed.targetIndices || ['main'],
        estimatedComplexity: parsed.estimatedComplexity || 'medium',
        explanation: parsed.explanation || 'Generated by Gemini.'
      };
    } catch (error) {
      console.error('Error generating SPL:', error);
      // Fallback
      return {
        splQuery: `index=* "${service}" "${input.naturalLanguagePrompt}"`,
        targetIndices: ['*'],
        estimatedComplexity: 'low',
        explanation: 'Fallback query due to generation error.'
      };
    }
  }
}